apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: '${deploymentName}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      serviceAccountName: default
      containers:
      - image: replace
        name: '${containerName}'
        volumeMounts:
         - name: vol
           mountPath: /tmp
        securityContext:
         capabilities:
          drop: 
          - NET_RAW
         allowPrivilegeEscalation: false
         runAsNonRoot: true
         runAsUser: 100
         readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
       - name: vol
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: '${serviceName}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: ClusterIP