apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: '${deploymentName}'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      serviceAccountName: default
      containers:
      - image: replace
        name: '${containerName}'
        volumeMounts:
         - name: vol
           mountPath: /tmp
        securityContext:
         runAsNonRoot: true
         runAsUser: 100
         readOnlyRootFilesystem: true
      volumes:
       - name: vol
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: '${serviceName}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: NodePort